
export namespace HapiGo {
    // Default Application
 export interface Application {}
    // Class
    
    // CLass Extension
    
    // Records

    // Function options
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface SearchOptionalParameter {
      /**
       * the app name to search
       */
      app?: string;
      /**
       * the file name to search
       */
      file?: string;
      /**
       * the keyword to search
       */
      clipboard?: string;
    }



}
export interface HapiGo extends HapiGo.Application {
    // Functions

     /**
      * search in HapiGo
      * @param directParameter search app/file/clipboard in HapiGo. If the search mode of HapiGo is mix, the command "search app" is equals to "search file".
      * @param option
      * 
      */
     search(directParameter: any, option?: HapiGo.SearchOptionalParameter): void;

     /**
      * translate in HapiGo
      * @param directParameter any text needs to translate
      * 
      */
     translate(directParameter: string, ): void;

     /**
      * run HapiGo snippet
      * @param directParameter run HapiGo snippet by uuid
      * 
      */
     snippet(directParameter: string, ): void;
}
