
export namespace Messages {
    // Default Application
 export interface Application {}
    // Class
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A participant for an account.
  */
 export interface Participant {
   /**
    * The participant's unique identifier. For example: 01234567-89AB-CDEF-0123-456789ABCDEF:+11234567890
    */
   id(): string;
   /**
    * The account for this participant.
    */
   account(): any;
   /**
    * The participant's name as it appears in the participant list.
    */
   name(): string;
   /**
    * The participant's handle.
    */
   handle(): string;
   /**
    * The first name from this participan's Contacts card, if available
    */
   firstName(): string;
   /**
    * The last name from this participant's Contacts card, if available
    */
   lastName(): string;
   /**
    * The full name from this participant's Contacts card, if available
    */
   fullName(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * An account that can be logged in to from this system
  */
 export interface Account {
   /**
    * A unique identifier for this account.
    */
   id(): string;
   /**
    * The name of this account as defined in Account preferences description field
    */
   description(): string;
   /**
    * Is the account enabled?
    */
   enabled(): boolean;
   /**
    * The connection status for this account.
    */
   connectionStatus(): any;
   /**
    * The type of service for this account
    */
   serviceType(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * An SMS or iMessage chat.
  */
 export interface Chat {
   /**
    * A guid identifier for this chat.
    */
   id(): string;
   /**
    * The chat's name as it appears in the chat list.
    */
   name(): string;
   /**
    * The account which is participating in this chat.
    */
   account(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A file being sent or received
  */
 export interface FileTransfer extends Item {
   /**
    * The guid for this file transfer
    */
   id(): string;
   /**
    * The name of this file
    */
   name(): string;
   /**
    * The local path to this file transfer
    */
   filePath(): any;
   /**
    * The direction in which this file is being sent
    */
   direction(): any;
   /**
    * The account on which this file transfer is taking place
    */
   account(): any;
   /**
    * The other participatant in this file transfer
    */
   participant(): any;
   /**
    * The total size in bytes of the completed file transfer
    */
   fileSize(): number;
   /**
    * The number of bytes that have been transferred
    */
   fileProgress(): number;
   /**
    * The current status of this file transfer
    */
   transferStatus(): any;
   /**
    * The date that this file transfer started
    */
   started(): any;
 }
  
   /**
  * A scriptable object.
  */
 export interface Item {
   /**
    * The class of the object.
    */
   class(): any;
   /**
    * All of the object's properties.
    */
   properties(): any;
 }
    
    // CLass Extension
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * Messages application.
  */
 export interface Application {}
    
    // Records

    // Function options
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface SendOptionalParameter {
      to: any;
    }



}
export interface Messages extends Messages.Application {
    // Functions

     /**
      * Sends a message to a participant or to a chat.
      * @param directParameter undefined
      * @param option
      * 
      */
     send(directParameter: {}, option?: Messages.SendOptionalParameter): void;

     /**
      * Login to all accounts.

      * 
      */
     login(): void;

     /**
      * Logout of all accounts.

      * 
      */
     logout(): void;
}
