
export namespace Reminders {
    // Default Application
 export interface Application {}
    // Class
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * An account in the Reminders application
  */
 export interface Account {
   /**
    * The unique identifier of the account
    */
   id(): string;
   /**
    * The name of the account
    */
   name(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A list in the Reminders application
  */
 export interface List extends Item {
   /**
    * The unique identifier of the list
    */
   id(): string;
   /**
    * The name of the list
    */
   name(): string;
   /**
    * The container of the list
    */
   container(): any;
   /**
    * The color of the list
    */
   color(): string;
   /**
    * The emblem icon name of the list
    */
   emblem(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A reminder in the Reminders application
  */
 export interface Reminder extends Item {
   /**
    * The name of the reminder
    */
   name(): string;
   /**
    * The unique identifier of the reminder
    */
   id(): string;
   /**
    * The container of the reminder
    */
   container(): any;
   /**
    * The creation date of the reminder
    */
   creationDate(): any;
   /**
    * The modification date of the reminder
    */
   modificationDate(): any;
   /**
    * The notes attached to the reminder
    */
   body(): string;
   /**
    * Whether the reminder is completed
    */
   completed(): boolean;
   /**
    * The completion date of the reminder
    */
   completionDate(): any;
   /**
    * The due date of the reminder; will set both date and time
    */
   dueDate(): any;
   /**
    * The all-day due date of the reminder; will only set a date
    */
   alldayDueDate(): any;
   /**
    * The remind date of the reminder
    */
   remindMeDate(): any;
   /**
    * The priority of the reminder; 0: no priority, 1–4: high, 5: medium, 6–9: low
    */
   priority(): number;
   /**
    * Whether the reminder is flagged
    */
   flagged(): boolean;
 }
  
  export interface Item {
    
  }
    
    // CLass Extension
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The Reminders application
  */
 export interface Application {
   /**
    * The default account in the Reminders application
    */
   defaultAccount(): any;
   /**
    * The default list in the Reminders application
    */
   defaultList(): any;
 }
    
    // Records

    // Function options

}
export interface Reminders extends Reminders.Application {
    // Functions

     /**
      * Show an object in the Reminders UI
      * @param directParameter The object to be shown
      * @return The object shown
      */
     show(directParameter: {}, ): void;
}
