
export namespace ScriptDebugger {
    // Default Application
 export interface Application {}
    // Class
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The application’s top-level scripting object.
  */
 export interface Application {
   /**
    * The name of the application.
    */
   name(): string;
   /**
    * Whether the application is active (frontmost).
    */
   frontmost(): boolean;
   /**
    * The version of the application.
    */
   version(): string;
   /**
    * Whether the Option key is being held down.
    */
   optionIsDown(): boolean;
   /**
    * Whether the Shift key is being held down.
    */
   shiftIsDown(): boolean;
   /**
    * Whether the Control key is being held down.
    */
   controlIsDown(): boolean;
   /**
    * No longer supported.
    */
   scriptBackgroundColorNoLongerSupported(): any;
   /**
    * All the object’s properties returned as a record.
    */
   properties(): any;
   /**
    * The user’s Scripts folder (in Application Support).
    */
   scriptsMenuFolder(): any;
   /**
    * The user’s Clippings folder (in Application Support).
    */
   clippingsMenuFolder(): any;
   /**
    * The user’s Templates folder (in Application Support).
    */
   templatesFolder(): any;
   /**
    * No longer supported.
    */
   applyHandlerFormattingNoLongerSupported(): boolean;
   /**
    * No longer supported.
    */
   handlerColorNoLongerSupported(): any;
   /**
    * Whether documents should open in tabs rather than in separate windows by default. Deprecated, replaced by the ‘prefer tabs’ property.
    */
   openInTabsDeprecated(): boolean;
   /**
    * Whether the version broswer is showing.
    */
   browsingVersions(): boolean;
   /**
    * The name of the active color theme. Changing the value will change the active color theme.
    */
   currentTheme(): string;
   /**
    * A list of the available color themes.
    */
   availableThemes(): any;
   /**
    * Whether the computer has the software required and suitable developer certificate to support notarization.
    */
   canNotarize(): any;
   /**
    * Whether the main script in applets should be locked after saving.
    */
   lockApplets(): any;
   /**
    * A fixed destination to be used when directly exporting any file run-only.
    */
   exportDestination(): any;
   /**
    * Whether all files should be directly exported to one designated folder, rather than to within their own container.
    */
   exportDestinationFixed(): any;
   /**
    * The name used for the immediate containing folder of a run-only export. This can include the following placeholders: [[filename]], [[short-date]], [[date]], [[GMT-date]], [[version]], and [[build]].
    */
   exportFolderName(): any;
   /**
    * Whether the default behavior is to try to open documents as tabs in an existing window, or to open them in windows of their own. The default value is ‘default’, which uses the value set in System Preferences.
    */
   preferTabs(): any;
   /**
    * Whether .scptd files should be saved with their source internally in both .rtf and .scpt format. When opening, the .rtf format is always preferred.
    */
   versionControlFriendly(): any;
   /**
    * If a bundle contains a file called “SD Script Notes.rtfd” in its Resources folder, it will be excluded from the exported version. Check this option if you want any such file to be copied separately to the export folder.
    */
   includeNotesOnExport(): any;
   /**
    * Whether a copy of the document’s source should be added to the export folder when a document is exported run-only. The file will have the same name as the export folder, with an extension of .applescript.
    */
   includeSourceOnExport(): any;
   /**
    * Whether search strings should be interpreted as regular expressions.
    */
   searchUsesRegex(): any;
   /**
    * Whether searches should match whole words.
    */
   searchMatchesWords(): any;
   /**
    * Whether searches should be case-sensitive.
    */
   searchIgnoresCase(): any;
   /**
    * Whether searches should loop to the top of a document.
    */
   searchWraps(): any;
   /**
    * The string to look for in a find or replace.
    */
   searchString(): any;
   /**
    * The replace string used in a find-and-replace.
    */
   searchReplaceString(): any;
   /**
    * Whether compiling escapes tabs and line breaks in strings.
    */
   escapesWhiteSpace(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A document.
  */
 export interface Document {
   /**
    * All the object’s properties returned as a record.
    */
   properties(): any;
   /**
    * The document’s name.
    */
   name(): string;
   /**
    * The document’s unique ID.
    */
   id(): string;
   /**
    * The document’s bundle ID
    */
   bundleID(): string;
   /**
    * A list of legacy Script Debugger library files linked to the document
    */
   legacyScriptLibraries(): any;
   /**
    * A list of legacy Script Debugger library files linked to the document
    */
   legacyScriptLibraryFiles(): any;
   /**
    * The document’s copyright string
    */
   copyright(): string;
   /**
    * The document’s marketing version string
    */
   marketingVersion(): string;
   /**
    * The document’s build number
    */
   buildNumber(): any;
   /**
    * Automatically increment the document's build number when saving?
    */
   autoincrementBuildNumber(): boolean;
   /**
    * Automatically increment the document's build number when exporting?
    */
   autoincrementBuildNumberOnExport(): boolean;
   /**
    * The name of the bundle document’s scripting definition file (missing value is none set).
    */
   scriptingDefinition(): any;
   /**
    * The name of the application document’s icon (.icns) file.
    */
   appletIcon(): any;
   /**
    * Whether the document been modified since it was last saved.
    */
   modified(): boolean;
   /**
    * The file’s location on disk (missing value if not saved).
    */
   fileSpec(): any;
   /**
    * Any value you want to associate with a document. (This information is not saved with the document.)
    */
   userData(): any;
   /**
    * The document’s file format.
    */
   scriptType(): any;
   /**
    * Whether the application should display its description as a splash screen on launch (if the script type is an application).
    */
   showStartup(): boolean;
   /**
    * Whether the application should stay open after running at launch (if the script type is an application).
    */
   stayOpen(): boolean;
   /**
    * What the script is currently doing (stopped, paused, running, etc.).
    */
   executionState(): any;
   /**
    * Whether the script has been compiled.
    */
   compiled(): boolean;
   /**
    * Whether the script has an open handler.
    */
   hasOpenHandler(): boolean;
   /**
    * Whether the script has a quit handler.
    */
   hasQuitHandler(): boolean;
   /**
    * Whether the script has an idle handler.
    */
   hasIdleHandler(): boolean;
   /**
    * Numeric code of the script’s most recent compilation or runtime error (or missing value if the script has compiled/run successfully).
    */
   lastErrorNumber(): number;
   /**
    * Text message of the script’s most recent compilation or runtime error (or missing value if the script has compiled/run successfully).
    */
   lastErrorMessage(): string;
   /**
    * Content and position of the script’s most recent compilation or runtime error (or missing value if the script has compiled/run successfully).
    */
   lastErrorRange(): any;
   /**
    * Partial result of the script’s most recent runtime error, as displayed in the error dialog’s Partial Result pane (or missing value if there was no partial result, or the script has compiled/run successfully).
    */
   lastErrorPartialResult(): any;
   /**
    * Offending object of the script’s most recent runtime error, as displayed in the error dialog’s Offending Object pane (or missing value if there was no offending object, or the script has compiled/run successfully).
    */
   lastErrorOffendingObject(): any;
   /**
    * Application of the script’s most recent runtime error, as displayed in the error dialog’s Application pane (or missing value if there was no application, or the script has compiled/run successfully).
    */
   lastErrorApplication(): any;
   /**
    * Expected type of the script’s most recent runtime error, as displayed in the error dialog’s Expected Type pane (or missing value if there was no expected type, or the script has compiled/run successfully).
    */
   lastErrorExpectedType(): any;
   /**
    * File URL of the script’s implicit target application (or missing value if none).
    */
   defaultTarget(): any;
   /**
    * A copy of the entire script object represented by the script.
    */
   script(): any;
   /**
    * The result produced by the script the last time it was run, or by the most recently executed line in debug mode (or missing value if the script has not been run).
    */
   lastResult(): any;
   /**
    * The document that is to serve as the script’s implicit parent (or missing value if none).
    */
   parentScript(): any;
   /**
    * Whether the script is in debug mode.
    */
   debuggerEnabled(): boolean;
   /**
    * Whether the script will pause at breakpoints in debug mode.
    */
   breakOnBreakpoints(): boolean;
   /**
    * Whether the script will pause at handled runtime errors in debug mode.
    */
   breakOnExceptions(): boolean;
   /**
    * Whether raw (“chevron”) Apple event codes are displayed in the script.
    */
   showRawSyntax(): boolean;
   /**
    * The current selection within the script’s source text.
    */
   selection(): any;
   /**
    * Whether code coverage marks are displayed in the gutter of the script (in debug mode).
    */
   showCodeCoverage(): boolean;
   /**
    * Whether the navigation bar is visible above the script.
    */
   navigationBarVisible(): boolean;
   /**
    * Width of the panes and inspectors tab to the right of the script (0 if tab display mode is none).
    */
   tabWidth(): number;
   /**
    * Which set of panes and inspectors is displayed to the right of the script.
    */
   tabDisplayMode(): any;
   /**
    * Which view (best, source, or AEPrint) the result explorer is in.
    */
   resultFormat(): any;
   /**
    * Whether line wrapping is turned on for the result pane of the script.
    */
   resultWrapLines(): boolean;
   /**
    * Whether invisible characters are displayed in the result pane of the script.
    */
   resultShowInvisibles(): boolean;
   /**
    * Whether tab stops are displayed in the result pane of the script.
    */
   resultShowTabStops(): boolean;
   /**
    * Whether space characters are displayed as dots in the result pane of the script (assuming invisible characters are being displayed in the result pane).
    */
   resultShowSpaces(): boolean;
   /**
    * Whether lists and records are pretty-printed in the result pane of the script.
    */
   resultPrettyPrint(): boolean;
   /**
    * Whether raw (“chevron”) Apple event codes are displayed in the result pane of the script.
    */
   resultShowRawSyntax(): boolean;
   /**
    * Whether the result bar is visible above the script.
    */
   resultBarVisible(): boolean;
   /**
    * Whether the event log pane is open below the script.
    */
   eventLogVisible(): boolean;
   /**
    * The height of the event log pane below the script.
    */
   eventLogHeight(): number;
   /**
    * The accumulated sum of start log and stop log commands.
    */
   eventLogLevel(): number;
   /**
    * Whether the scope bar is visible in the event log.
    */
   eventLogScopeBarVisible(): boolean;
   /**
    * Whether logged data should be appended to the current contents of the event log the next time the script runs.
    */
   appendToLog(): boolean;
   /**
    * Display format for events in the event log (source code, raw code, or AEPrint).
    */
   eventLogFormat(): any;
   /**
    * Whether the second pane of the event log is open, exploring the result of the selected event.
    */
   eventResultExplorerVisible(): boolean;
   /**
    * The width of the second pane of the event log, exploring the result of the selected event.
    */
   eventResultExplorerWidth(): number;
   /**
    * The position of the selection as a zero-based Cocoa range. Can be a list of two items or a record in the form {location:x, |length|:y}. Use this instead of the selection's “character range” if working in AppleScriptObjC.
    */
   selectionASObjCRange(): any;
   /**
    * The total duration displayed in the timer.
    */
   timerDuration(): any;
   /**
    * The Apple event count displayed in the timer.
    */
   eventCount(): number;
   /**
    * The script’s content, as text.
    */
   sourceText(): string;
   /**
    * The text of the script’s description.
    */
   description(): string;
   /**
    * The name of script libraries declared in use statements.
    */
   usedScriptLibraries(): any;
   /**
    * The script libraries declared in use statements as file references.
    */
   usedScriptLibraryFiles(): any;
   /**
    * The name of all script libraries embedded in the script's bundle. Returns missing value if the document is unsaved or not a bundle format (.scptd or .app).
    */
   embeddedScriptLibraries(): any;
   /**
    * The name of frameworks declared in use statements.
    */
   usedFrameworks(): any;
   /**
    * The frameworks declared in use statements as file references.
    */
   usedFrameworkFiles(): any;
   /**
    * The name of scripting additions used by this document.
    */
   usedScriptingAdditions(): any;
   /**
    * The scripting additions used by this document as file references.
    */
   usedScriptingAdditionFiles(): any;
   /**
    * The name of applications used by this document.
    */
   usedApplications(): any;
   /**
    * The document’s code sign identity. When running under macOS 11 Big Sur or later, ‘missing value’ means applets will be signed to run locally, which is the minimum requirement for universal apps. Under earlier version of macOS, ‘missing value’ means do not sign applets.
    */
   codesignIdentity(): any;
   /**
    * Whether codesigning is restricted to exporting run-only versions, or used for both saving and exporting. When saving under macOS 11 Big Sur or later, applets will still be signed even if this is false, as required for universal applets, but in such cases saving will sign the applet to run locally, ignoring any designated codesign identity. Applies only to applets (.app files), unless ‘codesign bundles too’ is true.
    */
   codesignOnExportOnly(): boolean;
   /**
    * Whether the codesigning settings for applets should also be applied to compiled script bundles (.scptd files).
    */
   codesignBundlesToo(): boolean;
   /**
    * When true, App Transport Security is disabled for an applet via an Info.plist NSAppTransportSecurity key entry. If an applet is configured with more complex settings than simply allowing arbitary loads, the property will return missing value.
    */
   allowArbitraryLoads(): boolean;
   /**
    * When true, an applet will run as a faceless background application.
    */
   backgroundOnly(): boolean;
   /**
    * If true when exporting an applet as run-only, any required libraries found in '~/Library/Script Libraries' or '/Library/Script Libraries' will be copied to the applet's Script Libraries folder.
    */
   embedUsedLibraries(): boolean;
   /**
    * If true when exporting an applet as run-only, any required non-Apple frameworks will be copied to the applet's Frameworks folder.
    */
   embedUsedFrameworks(): boolean;
   /**
    * If true when exporting an applet as run-only, any embedded scripts and Script Libraries will be made run-only.
    */
   embedRunOnly(): boolean;
   /**
    * For applets this sets the minimum version of macOS they will run under. Values should be in the format '10.n' or '10.n.n'. To remove, set to an empty string.
    */
   minimumSupportedOS(): string;
   /**
    * A list of the extensions (no dots) for files that a user will able to drag and drop on a droplet. An single entry consisting of an * means all types; an empty list means none.
    */
   dropletExtensions(): any;
   /**
    * A list of the Uniform Type Identifiers (UTIs) for conforming files that a user will able to drag and drop on a droplet. An empty list means none.
    */
   dropletUTIs(): any;
   /**
    * A name (less extension) to be used for the run-only version when performing a direct export. An empty string signifies that the name will be based on the exporting document's name.
    */
   exportName(): any;
   /**
    * Whether code folding indicators should appear in the gutter of the document's windows.
    */
   showCodeFolding(): boolean;
   /**
    * Its location on disk, if it has one, as a POSIX path string.
    */
   path(): string;
   /**
    * Whether line wrapping is turned on for the script.
    */
   wrapLines(): boolean;
   /**
    * Whether invisible characters are displayed in the script.
    */
   showInvisibles(): boolean;
   /**
    * Whether tab stops are displayed in the script.
    */
   showTabStops(): boolean;
   /**
    * Whether space characters are displayed as dots in the script (assuming invisible characters are being displayed).
    */
   showSpaces(): boolean;
   /**
    * Whether line numbers are displayed in the gutter of the script.
    */
   showLineNumbers(): boolean;
   /**
    * The event log window associated with the script (or missing value if the event log window is not open).
    */
   eventLogWindow(): any;
   /**
    * Whether the document window’s toolbar is visible.
    */
   toolbarVisible(): boolean;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A window; the superclass for Script Debugger’s actual window types.
  */
 export interface Window {
   /**
    * The window’s title.
    */
   name(): string;
   /**
    * The window’s unique ID.
    */
   id(): number;
   /**
    * The index of the window, ordered front to back. To change the order of windows, set a window’s index.
    */
   index(): number;
   /**
    * The window’s bounding rectangle (left, top, right, bottom, measured from the upper left of the screen).
    */
   bounds(): any;
   /**
    * Whether the window has a close box.
    */
   closeable(): boolean;
   /**
    * Whether the window can be minimized.
    */
   minimizable(): boolean;
   /**
    * Whether the window is currently minimized.
    */
   minimized(): boolean;
   /**
    * Whether the window can be resized.
    */
   resizable(): boolean;
   /**
    * Whether the window - or in the case of script window tab, its parent window - is currently visible.
    */
   visible(): boolean;
   /**
    * Whether the window can be zoomed.
    */
   zoomable(): boolean;
   /**
    * Whether the window is currently zoomed.
    */
   zoomed(): boolean;
   /**
    * Whether the window is showing full screen.
    */
   fullScreen(): boolean;
   /**
    * All the object’s properties returned as a record.
    */
   properties(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A way to refer to a range of text.
  */
 export interface SelectionObject {
   /**
    * The selected text. Set this to replace the text with different text.
    */
   contents(): string;
   /**
    * The position of the selection, expressed as a list: {character offset, length}. Set this to reposition the selection.
    */
   characterRange(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * An Apple event reply; used for a script result or a logged event result.
  */
 export interface ValueObject {
   /**
    * The actual value; it should not be necessary to use this property.
    */
   contents(): any;
   /**
    * The value’s label.
    */
   name(): string;
   /**
    * Whether the value has changed since the last time it was generated.
    */
   changed(): boolean;
   /**
    * The explorer window displaying this value (missing value if none).
    */
   window(): any;
   /**
    * File URL of the target application that generated this reply.
    */
   application(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The window displaying a document.
  */
 export interface ScriptWindow extends Window {
   /**
    * The script document being displayed in this window (in the frontmost tab, if the window has multiple documents).
    */
   currentDocument(): any;
   /**
    * Whether the window’s toolbar is visible.
    */
   toolbarVisible(): boolean;
   /**
    * The index of a script window tab within its parent script window, from left to right. If there are no tabs, the index will be 1.
    */
   tabIndex(): number;
   /**
    * Whether the window belongs to a window with more than one tab. If the window is tabbed, setting this property to false will detach this window so it becomes a top-level window by itself.
    */
   tabbed(): boolean;
   /**
    * The top-level script window this window belongs to. If the window has no tabs, or it is the active tab, the parent will be the window itself. Use this property to move script windows and tabs to other script windows.
    */
   parentWindow(): any;
   /**
    * The parent window’s bounding rectangle (left, top, right, bottom, measured from the upper left of the screen).
    */
   parentBounds(): any;
   /**
    * Whether a script window is visible, or in the case of a script window tab, whether it is the visible tab.
    */
   contentVisible(): boolean;
   /**
    * The current selection within the script’s source text.
    */
   selection(): any;
   /**
    * Whether code coverage marks are displayed in the gutter of the script (in debug mode).
    */
   showCodeCoverage(): boolean;
   /**
    * Whether the navigation bar is visible above the script.
    */
   navigationBarVisible(): boolean;
   /**
    * Whether the status bar is visible below the script.
    */
   statusBarVisible(): boolean;
   /**
    * Width of the panes and inspectors tab to the right of the script (0 if tab display mode is none).
    */
   tabWidth(): number;
   /**
    * Which set of panes and inspectors is displayed to the right of the script.
    */
   tabDisplayMode(): any;
   /**
    * Which view (best, source, or AEPrint) the result explorer is in.
    */
   resultFormat(): any;
   /**
    * Whether line wrapping is turned on for the result pane of the script.
    */
   resultWrapLines(): boolean;
   /**
    * Whether invisible characters are displayed in the result pane of the script.
    */
   resultShowInvisibles(): boolean;
   /**
    * Whether tab stops are displayed in the result pane of the script.
    */
   resultShowTabStops(): boolean;
   /**
    * Whether space characters are displayed as dots in the result pane of the script (assuming invisible characters are being displayed in the result pane).
    */
   resultShowSpaces(): boolean;
   /**
    * Whether lists and records are pretty-printed in the result pane of the script.
    */
   resultPrettyPrint(): boolean;
   /**
    * Whether raw (“chevron”) Apple event codes are displayed in the result pane of the script.
    */
   resultShowRawSyntax(): boolean;
   /**
    * Whether the result bar is visible above the script.
    */
   resultBarVisible(): boolean;
   /**
    * Whether the event log pane is open below the script.
    */
   eventLogVisible(): boolean;
   /**
    * The height of the event log pane below the script.
    */
   eventLogHeight(): number;
   /**
    * The accumulated sum of start log and stop log commands.
    */
   eventLogLevel(): number;
   /**
    * Whether the scope bar is visible in the event log.
    */
   eventLogScopeBarVisible(): boolean;
   /**
    * Whether logged data should be appended to the current contents of the event log the next time the script runs.
    */
   appendToLog(): boolean;
   /**
    * Display format for events in the event log (source code, raw code, or AEPrint).
    */
   eventLogFormat(): any;
   /**
    * Whether the second pane of the event log is open, exploring the result of the selected event.
    */
   eventResultExplorerVisible(): boolean;
   /**
    * The width of the second pane of the event log, exploring the result of the selected event.
    */
   eventResultExplorerWidth(): number;
   /**
    * Whether the window displays a progress bar when its script uses AppleScript's progress properties.
    */
   progressBarCanAppear(): boolean;
   /**
    * The position of the selection as a zero-based Cocoa range. Can be a list of two items or a record in the form {location:x, |length|:y}. Use this instead of the selection's “character range” if working in AppleScriptObjC.
    */
   selectionASObjCRange(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A tab belonging to a window.
  */
 export interface ScriptWindowTab extends ScriptWindow {}

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A handler in a script/script object.
  */
 export interface ScriptHandler {
   /**
    * The object’s class.
    */
   class(): any;
   /**
    * The handler’s index.
    */
   index(): any;
   /**
    * The name of the handler.
    */
   name(): any;
   /**
    * The object containing this object.
    */
   container(): any;
   /**
    * The contents of the handler.
    */
   contents(): any;
   /**
    * The handler’s contents, as text.
    */
   sourceText(): string;
   /**
    * The type of handler.
    */
   handlerType(): any;
   /**
    * All the object’s properties returned as a record.
    */
   properties(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A parameter to a handler.
  */
 export interface HandlerParameter {
   /**
    * The object’s class.
    */
   class(): any;
   /**
    * The parameter’s index.
    */
   index(): any;
   /**
    * The name of the parmeter.
    */
   name(): any;
   /**
    * The parameter's variable name within the handler.
    */
   variableName(): any;
   /**
    * The type of parameter.
    */
   parameterType(): any;
   /**
    * The object containing this object.
    */
   container(): any;
   /**
    * All the object’s properties returned as a record.
    */
   properties(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A property in a script/script object.
  */
 export interface ScriptProperty {
   /**
    * The object’s class.
    */
   class(): any;
   /**
    * The property’s index.
    */
   index(): any;
   /**
    * The name of the property.
    */
   name(): any;
   /**
    * The contents of the property.
    */
   contents(): any;
   /**
    * The property’s contents, as text.
    */
   sourceText(): string;
   /**
    * The object containing this object.
    */
   container(): any;
   /**
    * The type of data stored in the property.
    */
   type(): any;
   /**
    * The type of data stored in the property.
    */
   contentType(): any;
   /**
    * All the object’s properties returned as a record.
    */
   properties(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A dictionary window.
  */
 export interface DictionaryWindow extends Window {
   /**
    * File URL of the application whose dictionary window this is.
    */
   fileSpec(): any;
   /**
    * Which mode (Dictionary, Object Model, or Explorer) the window is displaying.
    */
   displayMode(): any;
   /**
    * Whether the window’s toolbar is visible.
    */
   toolbarVisible(): boolean;
   /**
    * Whether the dictionaries list is showing at the left of the dictionary window.
    */
   dictionariesListVisible(): boolean;
   /**
    * The width of the dictionaries list at the left of the dictionary window.
    */
   dictionariesListWidth(): number;
   /**
    * The current search string.
    */
   searchString(): string;
   /**
    * The current search string.
    */
   searchStringDeprecated(): string;
   /**
    * The current search options.
    */
   searchOptions(): any;
   /**
    * Whether there is currently a search (see on the search string property).
    */
   searchResultsVisible(): boolean;
   /**
    * Whether inherited properties and elements are included in class descriptions in the info pane.
    */
   showInherited(): any;
   /**
    * Whether extra documentation is displayed in the info pane.
    */
   showExtraDocumentation(): any;
   /**
    * Whether Raw (“Chevron”) Syntax is turned on, causing raw Apple event codes to appear in the info pane.
    */
   showRawSyntax(): boolean;
   /**
    * Which hierarchy diagram appears in Object Model view.
    */
   diagramHierarchy(): any;
   /**
    * The scaling factor of text in the dictionary window’s info pane (1.0 is “normal”).
    */
   textScale(): any;
   /**
    * Which view (best, source, or AEPrint) the dictionary window’s application explorer displays.
    */
   displayFormat(): any;
   /**
    * Whether line wrapping is turned on in the dictionary window’s application explorer.
    */
   wrapLines(): boolean;
   /**
    * Whether invisible characters are displayed in the dictionary window’s application explorer.
    */
   showInvisibles(): boolean;
   /**
    * Whether tab stops are displayed in the dictionary window’s application explorer.
    */
   showTabStops(): boolean;
   /**
    * Whether space characters are displayed as dots in the dictionary window’s application explorer (assuming invisible characters are being displayed).
    */
   showSpaces(): boolean;
   /**
    * Whether lists and records are pretty-printed in the dictionary window’s application explorer.
    */
   prettyPrint(): boolean;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * An explorer window.
  */
 export interface ExplorerWindow extends Window {
   /**
    * The value being displayed in the explorer window.
    */
   contents(): any;
   /**
    * Which view (best, source, or AEPrint) the explorer window displays.
    */
   displayFormat(): any;
   /**
    * Whether line wrapping is turned on in the explorer.
    */
   wrapLines(): boolean;
   /**
    * Whether invisible characters are displayed in the explorer.
    */
   showInvisibles(): any;
   /**
    * Whether tab stops are displayed in the explorer.
    */
   showTabStops(): boolean;
   /**
    * Whether space characters are displayed as dots in the explorer (assuming invisible characters are being displayed).
    */
   showSpaces(): boolean;
   /**
    * Whether the explorer’s value has changed since it was last produced.
    */
   changed(): boolean;
   /**
    * Whether lists and records are pretty-printed in the explorer.
    */
   prettyPrint(): boolean;
   /**
    * Whether raw (“chevron”) Apple event codes are displayed in the explorer.
    */
   showRawSyntax(): boolean;
   /**
    * Whether the window’s toolbar is visible.
    */
   toolbarVisible(): boolean;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * An event and its reply as recorded in the event log.
  */
 export interface EventLogEntry {
   /**
    * The command that generated the event, in source format.
    */
   eventSource(): string;
   /**
    * The result of the event.
    */
   eventResult(): any;
   /**
    * The result of the event in text form.
    */
   eventTextResult(): string;
   /**
    * The application to which the event was sent.
    */
   eventTarget(): any;
   /**
    * The document whose script generated the event.
    */
   document(): any;
   /**
    * Numeric code of the error returned from the event (or missing value if not an error).
    */
   eventErrorNumber(): number;
   /**
    * Text message of the error returned from the event (or missing value if not an error).
    */
   eventErrorMessage(): string;
   /**
    * The selection in the script of the text that generated the event, when paused during debugging (missing value otherwise).
    */
   eventSourceText(): any;
   /**
    * The accumulated sum of start log and stop log commands before this event, when paused during debugging (1 otherwise).
    */
   eventLogLevel(): number;
   /**
    * The time spent sending this event and receiving the reply. The total of event durations is the Events time in the timer.
    */
   eventDuration(): any;
   /**
    * The percentage of total script excution time spent sending this event and receiving the reply. The total of event percentages, subtracted from 100, is the AppleScript percentage in the timer.
    */
   eventPercentage(): any;
   /**
    * The elapsed script execution time when the event was sent.
    */
   eventStart(): any;
   /**
    * The elapsed script execution time when the reply was received.
    */
   eventEnd(): any;
   /**
    * All the object’s properties returned as a record.
    */
   properties(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The application to which an event was sent by a script.
  */
 export interface EventLogTarget {
   /**
    * Name of the application (or "'log' Commands").
    */
   name(): string;
   /**
    * File URL of the application.
    */
   fileSpec(): any;
   /**
    * The document whose script generated the event targeting the application.
    */
   document(): any;
   /**
    * The total duration of all events targeting the application.
    */
   targetDuration(): any;
   /**
    * Percentage of total event time spent targeting the application.
    */
   targetPercentage(): any;
   /**
    * All the object’s properties returned as a record.
    */
   properties(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * An event log window.
  */
 export interface EventLogWindow extends Window {
   /**
    * Whether the window’s toolbar is visible.
    */
   toolbarVisible(): boolean;
   /**
    * The document whose event log is shown in the window.
    */
   document(): any;
   /**
    * The event log entries selected in the window.
    */
   selectedEvents(): any;
   /**
    * The accumulated sum of start log and stop log commands.
    */
   eventLogLevel(): number;
   /**
    * Whether the scope bar is visible in the event log.
    */
   eventLogScopeBarVisible(): boolean;
   /**
    * Whether logged data should be appended to the current contents of the event log the next time the script runs.
    */
   appendToLog(): boolean;
   /**
    * Display format for events in the event log (source code, raw code, or AEPrint).
    */
   eventLogFormat(): any;
   /**
    * Whether the second pane of the event log is open, exploring the result of the selected event.
    */
   eventResultExplorerVisible(): boolean;
   /**
    * The width of the second pane of the event log, exploring the result of the selected event.
    */
   eventResultExplorerWidth(): number;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 export interface Reference {}

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A class
  */
 export interface Class {
   /**
    * The title of the class.
    */
   name(): string;
 }
    
    // CLass Extension
    
    // Records
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 export interface PrintSettings {
   /**
    * The number of copies of a document to be printed.
    */
   copies(): number;
   /**
    * Whether printed copies should be collated.
    */
   collating(): boolean;
   /**
    * The first page of the document to be printed.
    */
   startingPage(): number;
   /**
    * The last page of the document to be printed.
    */
   endingPage(): number;
   /**
    * Number of logical pages laid across a physical page.
    */
   pagesAcross(): number;
   /**
    * Number of logical pages laid out down a physical page.
    */
   pagesDown(): number;
   /**
    * How errors are handled.
    */
   errorHandling(): any;
   /**
    * For fax number.
    */
   faxNumber(): string;
   /**
    * For target printer.
    */
   targetPrinter(): string;
 }

    // Function options
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface OpenOptionalParameter {
      /**
       * Open a script file by recovering its backup text.
       */
      recoveringText?: boolean;
      /**
       * Open the script in a new tab within a particular script window. If provided, overrides the value for the ‘prefer tab’ parameter.
       */
      inWindow?: any;
      /**
       * Whether to try to open the document as a tab in an existing window, or open it in a window of its own. The default value is ‘default’, which uses the value set in Script Debugger's preferences. This parameter is ignored if the ‘in window’ parameter is present.
       */
      preferTab?: any;
      /**
       * Open the script's source code or its dictionary. Default is to show a dialog if a dictionary is found, otherwise open the script's source.
       */
      showing?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface CloseOptionalParameter {
      /**
       * Whether changes should be saved before closing.
       */
      saving?: any;
      /**
       * The file in which to save the document.
       */
      savingIn?: any;
      /**
       * The format for the saved file.
       */
      as?: any;
      /**
       * The type of line endings to use (when saving as a text script).
       */
      lineEndings?: any;
      /**
       * Whether the application should stay open after running at launch (when saving as an application).
       */
      stayOpen?: boolean;
      /**
       * Whether the application should display its description as a splash screen on launch (when saving as an application).
       */
      showStartupScreen?: boolean;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface SaveOptionalParameter {
      /**
       * The file in which to save the document.
       */
      in?: any;
      /**
       * The format for the saved file.
       */
      as?: any;
      /**
       * Whether the script should be exported as run-only (without bytecode, thus making decompilation and editing impossible).
       */
      runOnly?: boolean;
      /**
       * The type of line endings to use (when saving as a text script).
       */
      lineEndings?: any;
      /**
       * Whether the application should stay open after running at launch (when saving as an application).
       */
      stayOpen?: boolean;
      /**
       * Whether the application should display its description as a splash screen on launch (when saving as an application).
       */
      showStartupScreen?: boolean;
      /**
       * Whether bundled scripts and libraries should be also be exported as run-only (without bytecode, thus making decompilation and editing impossible). Only applies to script bundles and applets.
       */
      bundleRunOnly?: boolean;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface PrintOptionalParameter {
      /**
       * The print settings to use.
       */
      withProperties?: any;
      /**
       * Whether the print dialog should be shown.
       */
      printDialog?: boolean;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface QuitOptionalParameter {
      /**
       * Whether changed documents should be saved before closing.
       */
      saving?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface CountOptionalParameter {
      /**
       * The class of objects to be counted.
       */
      each?: any;
    }


    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface DuplicateOptionalParameter {
      /**
       * The location for the new object(s).
       */
      to?: any;
      /**
       * Properties to be set in the new duplicated object(s).
       */
      withProperties?: any;
    }


    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface MakeOptionalParameter {
      /**
       * The class of the new object.
       */
      new: any;
      /**
       * The location at which to insert the object.
       */
      at?: any;
      /**
       * The initial contents of the object.
       */
      withContents?: any;
      /**
       * When creating a new document, whether it should appear as a tab in an existing window, or in a window of its own. The default value is ‘default’, which uses the value set in Script Debugger's preferences.
       */
      preferTab?: any;
      /**
       * When creating a new document, whether it should be based on your default template, as set in General Preferences.
       */
      usingTemplate?: boolean;
      /**
       * The initial values for properties of the object.
       */
      withProperties?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface MoveOptionalParameter {
      /**
       * The new location for the object(s).
       */
      to: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface CompileOptionalParameter {
      /**
       * Whether the script error sheet should be displayed if there is a compilation error (the default is false).
       */
      showingErrors?: boolean;
    }








    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface DirectExportOptionalParameter {
      /**
       * The format for the saved file. The default is the same format as the file, or as an Apple Applet for .applescript files.
       */
      as?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface SearchOptionalParameter {
      /**
       * The type of search to conduct. The default is ‘find next’.
       */
      withAction?: any;
    }

}
export interface ScriptDebugger extends ScriptDebugger.Application {
    // Functions

     /**
      * Open a document or supplementary window.
      * @param directParameter The file(s) or windows(s) to be opened.
      * @param option
      * @return A reference to the resulting document, or missing value for a dictionary.
      */
     open(directParameter: {}, option?: ScriptDebugger.OpenOptionalParameter): void;

     /**
      * Close a document or window.
      * @param directParameter The document(s) or window(s) to close.
      * @param option
      * 
      */
     close(directParameter: any, option?: ScriptDebugger.CloseOptionalParameter): void;

     /**
      * Save a document.
      * @param directParameter The document(s) or window(s) to save.
      * @param option
      * 
      */
     save(directParameter: any, option?: ScriptDebugger.SaveOptionalParameter): void;

     /**
      * Print a document or window.
      * @param directParameter The file(s), document(s), or window(s) to be printed.
      * @param option
      * 
      */
     print(directParameter: {}, option?: ScriptDebugger.PrintOptionalParameter): void;

     /**
      * Quit the application.

      * @param option
      * 
      */
     quit(option?: ScriptDebugger.QuitOptionalParameter): void;

     /**
      * Return the number of elements of a particular class within an object.
      * @param directParameter The object whose elements are to be counted.
      * @param option
      * @return The number of elements.
      */
     count(directParameter: any, option?: ScriptDebugger.CountOptionalParameter): number;

     /**
      * Delete an object.
      * @param directParameter The object to delete.
      * 
      */
     delete(directParameter: any, ): void;

     /**
      * Copy object(s) and put the copies at a new location.
      * @param directParameter The object(s) to duplicate.
      * @param option
      * @return A reference to the newly created object(s).
      */
     duplicate(directParameter: any, option?: ScriptDebugger.DuplicateOptionalParameter): any;

     /**
      * Verify if an object exists.
      * @param directParameter The object in question.
      * @return True if it exists, false if not.
      */
     exists(directParameter: any, ): boolean;

     /**
      * Make a new object.

      * @param option
      * @return A reference to the newly created object.
      */
     make(option?: ScriptDebugger.MakeOptionalParameter): any;

     /**
      * Move object(s) to a new location.
      * @param directParameter The object(s) to move.
      * @param option
      * @return A reference to the moved object(s).
      */
     move(directParameter: any, option?: ScriptDebugger.MoveOptionalParameter): any;

     /**
      * Compile a script (document).
      * @param directParameter The script (document) to compile.
      * @param option
      * @return Whether the script compiled successfully. If not, your code can probe the various document “last error...” properties to learn what went wrong.
      */
     compile(directParameter: any, option?: ScriptDebugger.CompileOptionalParameter): boolean;

     /**
      * Begin or resume running a script (document).
      * @param directParameter The script (document) to execute.
      * 
      */
     execute(directParameter: any, ): void;

     /**
      * Abort running a script (document).
      * @param directParameter The script (document) to stop running.
      * 
      */
     halt(directParameter: any, ): void;

     /**
      * Reload a value displayed by an explorer.
      * @param directParameter The value to refresh.
      * 
      */
     refresh(directParameter: any, ): void;

     /**
      * Pause a script (document) at the next statement (in debug mode).
      * @param directParameter The script (document) to pause.
      * 
      */
     pause(directParameter: any, ): void;

     /**
      * Step a script (document) into a handler call (in debug mode).
      * @param directParameter The script (document) in which to step.
      * 
      */
     stepInto(directParameter: any, ): void;

     /**
      * Step a script (document) over a handler call (in debug mode).
      * @param directParameter The script (document) in which to step.
      * 
      */
     stepOver(directParameter: any, ): void;

     /**
      * Step a script (document) out of the current handler (in debug mode).
      * @param directParameter The script (document) in which to step.
      * 
      */
     stepOut(directParameter: any, ): void;

     /**
      * Export a run-only copy of a document.
      * @param directParameter The document to export.
      * @param option
      * @return The exported run-only file.
      */
     directExport(directParameter: any, option?: ScriptDebugger.DirectExportOptionalParameter): any;

     /**
      * Search the contents of a document, with the option to replace. The search string and other parameters are set as properties of the application.
      * @param directParameter The document to search.
      * @param option
      * @return Returns the selection range of the found match expressed as a list, {character offset, length}, or missing value if not found. It also selects the found text. When performing ‘replace all’ it returns the number of replacements made.
      */
     search(directParameter: any, option?: ScriptDebugger.SearchOptionalParameter): void;
}
