
export namespace Shortcuts {
    // Default Application
 export interface Application {}
    // Class
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * a shortcut in the Shortcuts application
  */
 export interface Shortcut {
   /**
    * the name of the shortcut
    */
   name(): string;
   /**
    * the shortcut's subtitle
    */
   subtitle(): string;
   /**
    * the unique identifier of the shortcut
    */
   id(): string;
   /**
    * the folder containing this shortcut
    */
   folder(): any;
   /**
    * the shortcut's color
    */
   color(): any;
   /**
    * the shortcut's icon
    */
   icon(): any;
   /**
    * indicates whether or not the shortcut accepts input data
    */
   acceptsInput(): boolean;
   /**
    * the number of actions in the shortcut
    */
   actionCount(): number;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * a folder containing shortcuts
  */
 export interface Folder {
   /**
    * the name of the folder
    */
   name(): string;
   /**
    * the unique identifier of the folder
    */
   id(): string;
 }
    
    // CLass Extension
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 export interface Application {}
    
    // Records

    // Function options
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface RunOptionalParameter {
      /**
       * the input to provide to the shortcut
       */
      withInput?: any;
    }

}
export interface Shortcuts extends Shortcuts.Application {
    // Functions

     /**
      * Run a shortcut. To run a shortcut in the background, without opening the Shortcuts app, tell 'Shortcuts Events' instead of 'Shortcuts'.
      * @param directParameter the shortcut to run
      * @param option
      * @return the result of the shortcut
      */
     run(directParameter: Shortcuts.Shortcut, option?: Shortcuts.RunOptionalParameter): any;
}
