
export namespace TickTick {
    // Default Application
 export interface Application {}
    // Class
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * The application's top-level scripting object.
  */
 export interface Application {
   /**
    * The name of the application.
    */
   name(): string;
   /**
    * Is this the active application?
    */
   frontmost(): boolean;
   /**
    * The version number of the application.
    */
   version(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A document.
  */
 export interface Document {
   /**
    * Its name.
    */
   name(): string;
   /**
    * Has it been modified since the last save?
    */
   modified(): boolean;
   /**
    * Its location on disk, if it has one.
    */
   file(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A window.
  */
 export interface Window {
   /**
    * The title of the window.
    */
   name(): string;
   /**
    * The unique identifier of the window.
    */
   id(): number;
   /**
    * The index of the window, ordered front to back.
    */
   index(): number;
   /**
    * The bounding rectangle of the window.
    */
   bounds(): any;
   /**
    * Does the window have a close button?
    */
   closeable(): boolean;
   /**
    * Does the window have a minimize button?
    */
   miniaturizable(): boolean;
   /**
    * Is the window minimized right now?
    */
   miniaturized(): boolean;
   /**
    * Can the window be resized?
    */
   resizable(): boolean;
   /**
    * Is the window visible right now?
    */
   visible(): boolean;
   /**
    * Does the window have a zoom button?
    */
   zoomable(): boolean;
   /**
    * Is the window zoomed right now?
    */
   zoomed(): boolean;
   /**
    * The document whose contents are displayed in the window.
    */
   document(): any;
 }
    
    // CLass Extension
    
    // Records
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 export interface PrintSettings {
   /**
    * the number of copies of a document to be printed
    */
   copies(): number;
   /**
    * Should printed copies be collated?
    */
   collating(): boolean;
   /**
    * the first page of the document to be printed
    */
   startingPage(): number;
   /**
    * the last page of the document to be printed
    */
   endingPage(): number;
   /**
    * number of logical pages laid across a physical page
    */
   pagesAcross(): number;
   /**
    * number of logical pages laid out down a physical page
    */
   pagesDown(): number;
   /**
    * the time at which the desktop printer should print the document
    */
   requestedPrintTime(): any;
   /**
    * how errors are handled
    */
   errorHandling(): any;
   /**
    * for fax number
    */
   faxNumber(): string;
   /**
    * for target printer
    */
   targetPrinter(): string;
 }

    // Function options

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface CloseOptionalParameter {
      /**
       * Should changes be saved before closing?
       */
      saving?: any;
      /**
       * The file in which to save the document, if so.
       */
      savingIn?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface SaveOptionalParameter {
      /**
       * The file in which to save the document.
       */
      in?: any;
      /**
       * The file format to use.
       */
      as?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface PrintOptionalParameter {
      /**
       * The print settings to use.
       */
      withProperties?: any;
      /**
       * Should the application show the print dialog?
       */
      printDialog?: boolean;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface QuitOptionalParameter {
      /**
       * Should changes be saved before quitting?
       */
      saving?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface CountOptionalParameter {
      /**
       * The class of objects to be counted.
       */
      each?: any;
    }


    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface DuplicateOptionalParameter {
      /**
       * The location for the new copy or copies.
       */
      to?: any;
      /**
       * Properties to set in the new copy or copies right away.
       */
      withProperties?: any;
    }


    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface MakeOptionalParameter {
      /**
       * The class of the new object.
       */
      new: any;
      /**
       * The location at which to insert the object.
       */
      at?: any;
      /**
       * The initial contents of the object.
       */
      withData?: any;
      /**
       * The initial values for properties of the object.
       */
      withProperties?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface MoveOptionalParameter {
      /**
       * The new location for the object(s).
       */
      to: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface TodayTasksOptionalParameter {
      /**
       * for statistical
       */
      from?: string;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface Next7DaysTasksOptionalParameter {
      /**
       * for statistical
       */
      from?: string;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface TasksInOptionalParameter {
      /**
       * for statistical
       */
      from?: string;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface SearchTasksOptionalParameter {
      /**
       * for statistical
       */
      from?: string;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface ProjectsOptionalParameter {
      /**
       * for statistical
       */
      from?: string;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface StartPomoOptionalParameter {
      /**
       * for statistical
       */
      from?: string;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface AddTaskOptionalParameter {
      /**
       * project id for new task, default is inbox.
       */
      toList?: string;
      /**
       * title for new task, default is empty.
       */
      title?: string;
      /**
       * description for new task, default is empty.
       */
      description?: string;
      /**
       * due date for new task, format: yyyy-MM-dd'T'HH:mm:sssZ
       */
      dueDate?: string;
      /**
       * if due date has no time, default is false
       */
      isAllday?: boolean;
      /**
       * integer for new task, none:0, low:1, medium:3, high:5, default is 0
       */
      priority?: number;
      /**
       * for statistical
       */
      from?: string;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface ToggleTaskOptionalParameter {
      /**
       * for statistical
       */
      from?: string;
    }

}
export interface TickTick extends TickTick.Application {
    // Functions

     /**
      * Open a document.
      * @param directParameter The file(s) to be opened.
      * @return The opened document(s).
      */
     open(directParameter: {}, ): void;

     /**
      * Close a document.
      * @param directParameter the document(s) or window(s) to close.
      * @param option
      * 
      */
     close(directParameter: any, option?: TickTick.CloseOptionalParameter): void;

     /**
      * Save a document.
      * @param directParameter The document(s) or window(s) to save.
      * @param option
      * 
      */
     save(directParameter: any, option?: TickTick.SaveOptionalParameter): void;

     /**
      * Print a document.
      * @param directParameter The file(s), document(s), or window(s) to be printed.
      * @param option
      * 
      */
     print(directParameter: {}, option?: TickTick.PrintOptionalParameter): void;

     /**
      * Quit the application.

      * @param option
      * 
      */
     quit(option?: TickTick.QuitOptionalParameter): void;

     /**
      * Return the number of elements of a particular class within an object.
      * @param directParameter The objects to be counted.
      * @param option
      * @return The count.
      */
     count(directParameter: any, option?: TickTick.CountOptionalParameter): number;

     /**
      * Delete an object.
      * @param directParameter The object(s) to delete.
      * 
      */
     delete(directParameter: any, ): void;

     /**
      * Copy an object.
      * @param directParameter The object(s) to copy.
      * @param option
      * 
      */
     duplicate(directParameter: any, option?: TickTick.DuplicateOptionalParameter): void;

     /**
      * Verify that an object exists.
      * @param directParameter The object(s) to check.
      * @return Did the object(s) exist?
      */
     exists(directParameter: any, ): boolean;

     /**
      * Create a new object.

      * @param option
      * @return The new object.
      */
     make(option?: TickTick.MakeOptionalParameter): any;

     /**
      * Move an object to a new location.
      * @param directParameter The object(s) to move.
      * @param option
      * 
      */
     move(directParameter: any, option?: TickTick.MoveOptionalParameter): void;

     /**
      * 

      * @param option
      * @return json string of tasks array
      */
     todayTasks(option?: TickTick.TodayTasksOptionalParameter): string;

     /**
      * 

      * @param option
      * @return json string of tasks array
      */
     next7DaysTasks(option?: TickTick.Next7DaysTasksOptionalParameter): string;

     /**
      * 
      * @param directParameter keywords
      * @param option
      * @return json string of tasks array
      */
     tasksIn(directParameter: {}, option?: TickTick.TasksInOptionalParameter): string;

     /**
      * 
      * @param directParameter keywords
      * @param option
      * @return json string of tasks array
      */
     searchTasks(directParameter: {}, option?: TickTick.SearchTasksOptionalParameter): string;

     /**
      * 

      * @param option
      * @return json string of projects array
      */
     projects(option?: TickTick.ProjectsOptionalParameter): string;

     /**
      * 
      * @param directParameter duration(mins, 5~180)
      * @param option
      * 
      */
     startPomo(directParameter?: {}, option?: TickTick.StartPomoOptionalParameter): void;

     /**
      * 

      * @param option
      * @return Whether the task was successfully added
      */
     addTask(option?: TickTick.AddTaskOptionalParameter): boolean;

     /**
      * 
      * @param directParameter task id
      * @param option
      * @return Whether the task was successfully toggle
      */
     toggleTask(directParameter: {}, option?: TickTick.ToggleTaskOptionalParameter): boolean;
}
