
export namespace VLC {
    // Default Application
 export interface Application {}
    // Class
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * An application's top level scripting object.
  */
 export interface Application extends Item {
   /**
    * Is this the frontmost (active) application?
    */
   frontmost(): boolean;
   /**
    * The name of the application.
    */
   name(): string;
   /**
    * The version of the application.
    */
   version(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A color.
  */
 export interface Color extends Item {}

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A document.
  */
 export interface Document extends Item {
   /**
    * Has the document been modified since the last save?
    */
   modified(): boolean;
   /**
    * The document's name.
    */
   name(): string;
   /**
    * The document's path.
    */
   path(): string;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A scriptable object.
  */
 export interface Item {
   /**
    * The class of the object.
    */
   class(): any;
   /**
    * All of the object's properties.
    */
   properties(): any;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * A window.
  */
 export interface Window extends Item {
   /**
    * The bounding rectangle of the window.
    */
   bounds(): any;
   /**
    * Whether the window has a close box.
    */
   closeable(): boolean;
   /**
    * The document whose contents are being displayed in the window.
    */
   document(): any;
   /**
    * Whether the window floats.
    */
   floating(): boolean;
   /**
    * The unique identifier of the window.
    */
   id(): number;
   /**
    * The index of the window, ordered front to back.
    */
   index(): number;
   /**
    * Whether the window can be miniaturized.
    */
   miniaturizable(): boolean;
   /**
    * Whether the window is currently miniaturized.
    */
   miniaturized(): boolean;
   /**
    * Whether the window is the application's current modal window.
    */
   modal(): boolean;
   /**
    * The full title of the window.
    */
   name(): string;
   /**
    * Whether the window can be resized.
    */
   resizable(): boolean;
   /**
    * Whether the window has a title bar.
    */
   titled(): boolean;
   /**
    * Whether the window is currently visible.
    */
   visible(): boolean;
   /**
    * Whether the window can be zoomed.
    */
   zoomable(): boolean;
   /**
    * Whether the window is currently zoomed.
    */
   zoomed(): boolean;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * Represents an inline text attachment. This class is used mainly for make commands.
  */
 export interface Attachment extends TextCtxt {
   /**
    * The path to the file for the attachment
    */
   fileName(): string;
 }
  
   export interface TextCtxt {
   /**
    * The color of the first character.
    */
   color(): any;
   /**
    * The name of the font of the first character.
    */
   font(): string;
   /**
    * The size in points of the first character.
    */
   size(): number;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * This subdivides the text into chunks that all have the same attributes.
  */
 export interface AttributeRun extends Item {
   /**
    * The color of the first character.
    */
   color(): any;
   /**
    * The name of the font of the first character.
    */
   font(): string;
   /**
    * The size in points of the first character.
    */
   size(): number;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * This subdivides the text into characters.
  */
 export interface Character extends Item {
   /**
    * The color of the first character.
    */
   color(): any;
   /**
    * The name of the font of the first character.
    */
   font(): string;
   /**
    * The size in points of the first character.
    */
   size(): number;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * This subdivides the text into paragraphs.
  */
 export interface Paragraph extends Item {
   /**
    * The color of the first character.
    */
   color(): any;
   /**
    * The name of the font of the first character.
    */
   font(): string;
   /**
    * The size in points of the first character.
    */
   size(): number;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * Rich (styled) text
  */
 export interface Text extends Item {
   /**
    * The color of the first character.
    */
   color(): any;
   /**
    * The name of the font of the first character.
    */
   font(): string;
   /**
    * The size in points of the first character.
    */
   size(): number;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * This subdivides the text into words.
  */
 export interface Word extends Item {
   /**
    * The color of the first character.
    */
   color(): any;
   /**
    * The name of the font of the first character.
    */
   font(): string;
   /**
    * The size in points of the first character.
    */
   size(): number;
 }

 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 export interface PrintSettings {
   /**
    * the number of copies of a document to be printed
    */
   copies(): number;
   /**
    * Should printed copies be collated?
    */
   collating(): boolean;
   /**
    * the first page of the document to be printed
    */
   startingPage(): number;
   /**
    * the last page of the document to be printed
    */
   endingPage(): number;
   /**
    * number of logical pages laid across a physical page
    */
   pagesAcross(): number;
   /**
    * number of logical pages laid out down a physical page
    */
   pagesDown(): number;
   /**
    * the time at which the desktop printer should print the document
    */
   requestedPrintTime(): any;
   /**
    * how errors are handled
    */
   errorHandling(): any;
   /**
    * for fax number
    */
   faxNumber(): string;
   /**
    * for target printer
    */
   targetPrinter(): string;
 }
    
    // CLass Extension
 /**
  * This file was automatically generated by json-schema-to-typescript.
  * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
  * and run json-schema-to-typescript to regenerate this file.
  */

 /**
  * VLC's top level scripting object
  */
 export interface Application {
   /**
    * The audio desynchronization preference from -2147483648 to 2147483647, where 0 is default.
    */
   audioDesync(): number;
   /**
    * The volume of the current playlist item from 0 to 512, where 256 is 100%.
    */
   audioVolume(): number;
   /**
    * The current time of the current playlist item in seconds.
    */
   currentTime(): number;
   /**
    * The duration of the current playlist item in seconds.
    */
   durationOfCurrentItem(): number;
   /**
    * Indicates wheter fullscreen is enabled or not.
    */
   fullscreenMode(): boolean;
   /**
    * Is VLC currently muted?
    */
   muted(): boolean;
   /**
    * Name of the current playlist item.
    */
   nameOfCurrentItem(): string;
   /**
    * Path to the current playlist item.
    */
   pathOfCurrentItem(): string;
   /**
    * Indicates whether a DVD menu is currently being shown.
    */
   playbackShowsMenu(): boolean;
   /**
    * Is VLC playing an item?
    */
   playing(): boolean;
 }
    
    // Records

    // Function options
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface CloseOptionalParameter {
      /**
       * Specifies whether changes should be saved before closing.
       */
      saving?: any;
      /**
       * The file in which to save the object.
       */
      savingIn?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface CountOptionalParameter {
      /**
       * The class of objects to be counted.
       */
      each?: any;
    }


    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface DuplicateOptionalParameter {
      /**
       * The location for the new object(s).
       */
      to?: any;
      /**
       * Properties to be set in the new duplicated object(s).
       */
      withProperties?: any;
    }



    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface MakeOptionalParameter {
      /**
       * The class of the new object.
       */
      new: any;
      /**
       * The location at which to insert the object.
       */
      at?: any;
      /**
       * The initial data for the object.
       */
      withData?: any;
      /**
       * The initial values for properties of the object.
       */
      withProperties?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface MoveOptionalParameter {
      /**
       * The new location for the object(s).
       */
      to: any;
    }


    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface PrintOptionalParameter {
      /**
       * Should the application show the Print dialog?
       */
      printDialog?: boolean;
      /**
       * the print settings
       */
      withProperties?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface QuitOptionalParameter {
      /**
       * Specifies whether changes should be saved before quitting.
       */
      saving?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface SaveOptionalParameter {
      /**
       * The file type in which to save the data.
       */
      as?: string;
      /**
       * The file in which to save the object.
       */
      in?: any;
    }

    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export interface SetOptionalParameter {
      /**
       * The new value.
       */
      to: any;
    }


















}
export interface VLC extends VLC.Application {
    // Functions

     /**
      * Close an object.
      * @param directParameter the object for the command
      * @param option
      * 
      */
     close(directParameter: any, option?: VLC.CloseOptionalParameter): void;

     /**
      * Return the number of elements of a particular class within an object.
      * @param directParameter the object for the command
      * @param option
      * @return undefined
      */
     count(directParameter: any, option?: VLC.CountOptionalParameter): number;

     /**
      * Delete an object.
      * @param directParameter the object for the command
      * 
      */
     delete(directParameter: any, ): void;

     /**
      * Copy object(s) and put the copies at a new location.
      * @param directParameter the object for the command
      * @param option
      * 
      */
     duplicate(directParameter: any, option?: VLC.DuplicateOptionalParameter): void;

     /**
      * Verify if an object exists.
      * @param directParameter the object for the command
      * @return undefined
      */
     exists(directParameter: any, ): boolean;

     /**
      * Get the data for an object.
      * @param directParameter the object for the command
      * @return undefined
      */
     get(directParameter: any, ): any;

     /**
      * Make a new object.

      * @param option
      * @return undefined
      */
     make(option?: VLC.MakeOptionalParameter): any;

     /**
      * Move object(s) to a new location.
      * @param directParameter the object for the command
      * @param option
      * 
      */
     move(directParameter: any, option?: VLC.MoveOptionalParameter): void;

     /**
      * Open an object.
      * @param directParameter The file(s) to be opened.
      * @return undefined
      */
     open(directParameter: any, ): VLC.Document;

     /**
      * Print an object.
      * @param directParameter The file(s) or document(s) to be printed.
      * @param option
      * 
      */
     print(directParameter: any, option?: VLC.PrintOptionalParameter): void;

     /**
      * Quit an application.

      * @param option
      * 
      */
     quit(option?: VLC.QuitOptionalParameter): void;

     /**
      * Save an object.
      * @param directParameter the object for the command
      * @param option
      * 
      */
     save(directParameter: any, option?: VLC.SaveOptionalParameter): void;

     /**
      * Set an object's data.
      * @param directParameter the object for the command
      * @param option
      * 
      */
     set(directParameter: any, option?: VLC.SetOptionalParameter): void;

     /**
      * Activates the currently focussed menu item.
      * @param directParameter the object for the command
      * 
      */
     activateMenuItem(directParameter: any, ): void;

     /**
      * Toggle between fullscreen and windowed mode.
      * @param directParameter the object for the command
      * 
      */
     fullscreen(directParameter: any, ): void;

     /**
      * Get a URL.
      * @param directParameter the object for the command
      * 
      */
     getURL(directParameter: any, ): void;

     /**
      * Moves the menu focus down.
      * @param directParameter the object for the command
      * 
      */
     moveMenuFocusDown(directParameter: any, ): void;

     /**
      * Moves the menu focus to the left.
      * @param directParameter the object for the command
      * 
      */
     moveMenuFocusLeft(directParameter: any, ): void;

     /**
      * Moves the menu focus to the right.
      * @param directParameter the object for the command
      * 
      */
     moveMenuFocusRight(directParameter: any, ): void;

     /**
      * Moves the menu focus up.
      * @param directParameter the object for the command
      * 
      */
     moveMenuFocusUp(directParameter: any, ): void;

     /**
      * Mute the audio or unmute it if it was muted.
      * @param directParameter the object for the command
      * 
      */
     mute(directParameter: any, ): void;

     /**
      * Go to the next item in the playlist or the next chapter in the DVD/VCD.
      * @param directParameter the object for the command
      * 
      */
     next(directParameter: any, ): void;

     /**
      * Open a media URL.
      * @param directParameter the object for the command
      * 
      */
     openURL(directParameter: any, ): void;

     /**
      * Start playing the current playlistitem or pause it when it is already playing.
      * @param directParameter the object for the command
      * 
      */
     play(directParameter: any, ): void;

     /**
      * Go to the previous item in the playlist or the previous chapter in the DVD/VCD.
      * @param directParameter the object for the command
      * 
      */
     previous(directParameter: any, ): void;

     /**
      * Step the current playlist item backward the specified step width (default is 2) (1=extraShort, 2=short, 3=medium, 4=long).
      * @param directParameter the object for the command
      * 
      */
     stepBackward(directParameter: any, ): void;

     /**
      * Step the current playlist item forward the specified step width (default is 2) (1=extraShort, 2=short, 3=medium, 4=long).
      * @param directParameter the object for the command
      * 
      */
     stepForward(directParameter: any, ): void;

     /**
      * Stop playing the current playlist item.
      * @param directParameter the object for the command
      * 
      */
     stop(directParameter: any, ): void;

     /**
      * Bring the volume down by one step. There are 32 steps from 0 to 400% volume.
      * @param directParameter the object for the command
      * 
      */
     volumeDown(directParameter: any, ): void;

     /**
      * Bring the volume up by one step. There are 32 steps from 0 to 400% volume.
      * @param directParameter the object for the command
      * 
      */
     volumeUp(directParameter: any, ): void;
}
